/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import AdjListGraph.App;
import AdjListGraph.Client;
import javax.swing.JOptionPane;

/**
 * Descripción: interface gráfica para que el cliente realice su compra
 * @author Catalina Matheus
 * @version: 19/02/2023
 */
public class RegisterClient extends javax.swing.JFrame {
    
    private App app;
    
    /**
     * Creates new form RegisterClient
     */
    public RegisterClient() {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null); 
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        inputName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        inputLastName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        inputId = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        inputLocation = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel1.setText("REALIZAR PEDIDO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 120, 40));

        jLabel2.setText("Por favor, ingrese los siguientes datos personales: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 330, 30));

        jLabel3.setText("Nombre: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));
        getContentPane().add(inputName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 430, -1));

        jLabel4.setText("Apellido: ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, 20));
        getContentPane().add(inputLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 430, -1));

        jLabel5.setText("Cédula: ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));
        getContentPane().add(inputId, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 430, -1));

        jLabel6.setText("Dirección para el envío: ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));
        getContentPane().add(inputLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 340, -1));

        jToggleButton1.setText("REGISTRAR DATOS");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 420, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        String clientName; 
        String clientLastName; 
        int clientId; 
        String clientLocation; 
        
        
//        if(inputName.getText().equals("")){
//            inputName.setText("Debe colocar su nombre");
//        }if(inputLastName.getText().equals("")){
//            inputLastName.setText("Debe colocar su apellido"); 
//        }if(inputId.getText().equals("")){
//            inputId.setText("Debe colocar su cédula"); 
//        }if(inputLocation.getText().equals("")){
//            inputLocation.setText("Debe colocar la dirección donde quiere que envié el pedido");
//        }
        
        
        
        try{
            
            clientName = inputName.getText(); 
            if (clientName. equals("")) throw new Exception("Debe colocar su nombre.");
            inputName.setText(""); 
            
        
            clientLastName = inputLastName.getText(); 
            if (clientLastName.equals("")) throw new Exception("Debe colocar su apellido."); 
            inputLastName.setText(""); 
            
            clientId = Integer.parseInt(inputId.getText()); 
            inputId.setText(""); 
            
            clientLocation = inputLocation.getText(); 
            if (clientLocation.equals("")) throw new Exception("Debe colocar una dirección donde se mandarán los productos seleccionados."); 
            inputLocation.setText(""); 
            
            
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "No se logró registrar al cliente"); 
            inputName.setText(""); 
            inputLastName.setText(""); 
            inputId.setText(""); 
            inputLocation.setText(""); 
            
            
        
        }
        
       
        
        
        
        
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField inputId;
    private javax.swing.JTextField inputLastName;
    private javax.swing.JTextField inputLocation;
    private javax.swing.JTextField inputName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
